config/routes.rb
Rails.application.routes.draw do
    root "sessions#new"
    get '/:locale'   => 'sessions#new',as:"locale" 
    get '/' => redirect("/ja")
    post '/',        to: 'sessions#create'
    get 'password_resets/new'
    get 'password_resets/edit'
  scope ":/locale", locale:/en|ja/ do
  # scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get  '/',        to: 'sessions#new'
    post '/',        to: 'sessions#create'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/privacy', to: 'static_pages#privacy'
    get  '/term',    to: 'static_pages#term'
    get  '/language',to: 'static_pages#language'
    get  '/search',  to: 'static_pages#search'
    get  '/searchresult', to: 'static_pages#searchresult'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    delete '/logout',    to: 'sessions#destroy'
    get  '/tester',      to: 'tests#new'
    post '/tester',      to: 'tests#create'
    get  '/mytests',     to: 'tests#my_index'
    get  '/mytests/:id', to: 'tests#my_show'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tests do
      resources :questions do
        member do
          get :answerring
          post :post_answerring
        end
        resources :selects, :answers, only: [:new, :create, :edit, :destroy]
      end
    end
    resources :testeds do
      resources :tests do
        resources :answers, only: [:index, :show, :destroy]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :selects, dependent: :destroy
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true
  belongs_to :answer, optional: true
  mount_uploader :picture, PictureUploader
  validates :test_id, presence: true
  validates :Q, presence: true
  validate  :picture_size

  private
    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  include QuestionsHelper
  
  def new
    @user = current_user
    @test = Test.find(params[:test_id])
    @question = Question.new
  end

  def create
    @test = Test.find(params[:test_id])
    @question = @test.questions.build(question_params)
    if @question.save
      flash[:success] = "Question created!"
      redirect_to request.referrer || mytests_path
    else
      redirect_to request.referrer || mytests_path
    end
  end

  def edit
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:success] = "Question deleted"
    redirect_to new_test_question_path || mytests_path
  end
  
  def answerring
    @user = current_user
    @test = Test.find(params[:test_id])
    @question = @test.questions.find(params[:id])
    answer_selects(@question)
    now_answer(@test)  # 回答すると、次の質問にジャンプする。AnswersHelper参照。
    @answers = []
    (@ia+1).times do
      @answer = Answer.new
      @answers = @answers.push(@answer)
    end
  end
  
  def post_answerring
    @user = current_user
    @test = Test.find(params[:test_id])
    @question = @test.questions.find(params[:id])
    @answer = @question.answers.build(answer_params)
    answer_selects(@question)
    now_answer(@test)  # 回答すると、次の質問にジャンプする。AnswersHelper参照。
    if @answer.save
      if @next_question == nil
        tested_id = @user.id
        redirect_to tested_test_answers_path(tested_id, @test.id)  # 採点ページにジャンプする。
      else
        redirect_to answerring_test_question_path(@test, @next_question.id)
      end
    else
      redirect_to request.referrer || mytests_path
    end
  end
  
  private
    def question_params
      params.require(:question).permit(:test_id, :Q, :correct_A, :point, :picture)
    end
    
    def answer_params
      params.require(:answer).permit(:tested_id, :select_A, :select_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def answers_show(test)
    @answers = []
    @questions = []
    @test.questions.each_with_index do |question, iq|
      @questions = @questions.push(question)
      question.answers.each_with_index do |answer, ia|
        @answers = @answers.push(answer)
      end
    end
  end
  
  def answer_selects(question)
    @selects = []
    question.selects.each_with_index do |select, ia|
      @selects = @selects.push(select)
      @ia = ia
    end
  end
  
  def now_answer(test)
    questions = []
    @test.questions.each_with_index do |question, i|
      questions.push(question)
      if question.id == params[:id].to_i
        @question_num = i+1
      end
    end
    @next_question = questions[@question_num]
  end
end

app/views/questions/_create_question.html.erb
<aside class = "col-md-4 white_block">
  <section = "user_info">
    <%= gravatar_for user, size: 50 %>
    <%= user.name %>
  </section>
  <div class = "quiz">
    <%= form_for(question, url: { action: :create }) do |f| %>
      <%= f.label :問題 %>
      <%= f.text_area :Q, class: 'form-control', size: "30x6" %>
      <%= f.submit "Create Question", class: "btn btn-primary" %>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'%>
      </span>
    <% end %>
  </div>
</aside>
<!--以下、画像投稿用のjavascript-->
<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/questions/answerring.html.erb
<% provide(:title, 'Take a test') %>
<div class="white_belt"><h1><%= yield(:title) %></h1></div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="white">
      <%= form_for(@question, url: post_answerring_test_question_path(@test.id, @question.id), method: :post) do |f| %>
        <div class="radio_btn space-bottom-20">
          <li><%= t :問題 %>（<%= @question_num %>）</li>
          <div class="quiz"><%= @question.Q %></div>
          <span class="content">
            <%= image_tag @question.picture.url if @question.picture? %>
          </span>
          <div class="space-pad-10"></div>
          <div class="quiz"><%= t :選択肢 %></div>
          <% for i in 0..@ia do %>
            <%= fields_for @answers[i] do |f_answer| %>
              <%= f_answer.hidden_field :tested_id, :value => @user.id %>
              <%= f_answer.hidden_field :select_A, :value => 1 %>
              <p><%= "(#{ i+1 })" %></p>
              <%= f_answer.radio_button :select_id, @selects[i].id %>
              <%= f_answer.label :select_id, @selects[i].content,
                  {value: @selects[i].id, style: "display: inline-block;"} %>
            <% end %>
          <% end %>
        </div>
        <%= f.submit "Next", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/edit.html.erb
<h1>Questions#edit</h1>
<p>Find me in app/views/questions/edit.html.erb</p>

app/views/questions/new.html.erb
<% provide(:title, 'Create Question') %>
<div class="white_belt"><h1><%= yield(:title) %></h1></div>
<div class="row">
  <%= render 'create_question', user: @user, test: @test, question: @question %>
  <% if @user.tests.any? %>
    <div class = "menu">
      <div class="col-md-7 white_block">
        <div align="center">
          <h4><%= t :分野 %>：<%= @test.subject %></h4>
          <h4><%= t :タイトル %>：<%= @test.title %></h4>
        </div>
        <% @test.questions.each_with_index do |question, i| %>
          <div class="microposts">
            <li><%= t :問題 %>（<%= i+1 %>）</li>
            <%= question.Q %>
          </div>
          <div align="right">
            <%= link_to "delete question", test_question_path(@test,question),
                method: :delete,  data: { confirm: "You sure?" } %>
          </div>
          <% validate_select = 0 %>
            <% question.selects.each_with_index do |select, ia| %>
              <div class="quiz">
                <%= t :選択肢 %>（<%= ia+1%>）
                <%= select.judge == 1 ? "正解：" : "不正解：" %>
                <%= select.content %>
              </div>
              <% validate_select += select.judge %>
            <% end %>
          <% if validate_select == 0 %>
            <div class="alert alert-danger">
              <%= t :正解を用意してください %>
            </div>
          <% end %>
          <div align="right">
            <%= link_to "create selects", new_test_question_select_path(@test,question) %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>