config/routes.rb
Rails.application.routes.draw do
    root "sessions#new"
    get '/:locale'   => 'sessions#new',as:"locale" 
    get '/' => redirect("/ja")
    post '/',        to: 'sessions#create'
    get 'password_resets/new'
    get 'password_resets/edit'
  scope ":/locale", locale:/en|ja/ do
  # scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    get  '/',        to: 'sessions#new'
    post '/',        to: 'sessions#create'
    get  '/help',    to: 'static_pages#help'
    get  '/about',   to: 'static_pages#about'
    get  '/privacy', to: 'static_pages#privacy'
    get  '/term',    to: 'static_pages#term'
    get  '/language',to: 'static_pages#language'
    get  '/search',  to: 'static_pages#search'
    get  '/searchresult', to: 'static_pages#searchresult'
    get  '/signup',  to: 'users#new'
    post '/signup',  to: 'users#create'
    delete '/logout',    to: 'sessions#destroy'
    get  '/tester',      to: 'tests#new'
    post '/tester',      to: 'tests#create'
    get  '/mytests',     to: 'tests#my_index'
    get  '/mytests/:id', to: 'tests#my_show'
    resources :users
    resources :account_activations, only: [:edit]
    resources :password_resets,     only: [:new, :create, :edit, :update]
    resources :tests do
      resources :questions do
        member do
          get :answerring
          post :post_answerring
        end
        resources :selects, :answers, only: [:new, :create, :edit, :destroy]
      end
    end
    resources :testeds do
      resources :tests do
        resources :answers, only: [:index, :show, :destroy]
      end
    end
  end
end

app/models/select.rb
class Select < ApplicationRecord
  belongs_to :question
  delegate :answer,  to: :question
end

app/controllers/selects_controller.rb
class SelectsController < ApplicationController
  before_action :logged_in_user, only: [:create]
  
  def new
    @user = current_user
    @test = Test.find(params[:test_id])
    @question = @test.questions.find(params[:question_id])
    @select = Select.new
  end
  
  def create
    @test = Test.find(params[:test_id])
    @question = @test.questions.find(params[:question_id])
    @select = @question.selects.build(select_params)
    if @select.save
      flash[:success] = "Select created!"
      redirect_to request.referrer || mytests_path
    else
      redirect_to request.referrer || mytests_path
    end
  end
  
  def edit
    
  end
  
  def destroy
    @select = Select.find(params[:id])
    @select.destroy
    flash[:success] = "Select deleted"
    redirect_to request.referrer || mytests_path
  end
  
  private
    def select_params
      params.require(:select).permit(:content, :judge)
    end
end

app/helpers/selects_helper.rb
module SelectsHelper
end

app/views/selects/_create_select.html.erb
<aside class = "col-md-4 white_block">
  <section = "user_info">
    <%= gravatar_for user, size: 50 %>
    <%= user.name %>
  </section>
  <div class = "quiz">
    <%= form_for select, url: test_question_selects_path(test, question) do |f| %>
      <%= t :分野 %>：　<%= test.subject %><br>
      <%= t :タイトル %>：　<%= test.title %><br>
      <%= t :問題 %>：　<%= question.Q %><br>
      <br>
      <%= f.label :質問 %>
      <%= f.text_area :content %>
        <div class= "sidemenu_box"><%= f.check_box :judge %></div>
        <div class= "right"><%= t :正解なら、チェックを入れてください %></div>
      <%= f.submit "Create Selection", class: "btn btn-primary" %>
    <% end %>
  </div>
</aside>

app/views/selects/new.html.erb
<% provide(:title, 'Create Selection') %>
<div class="white_belt"><h1><%= yield(:title) %></h1></div>
<div class="row">
  <%= render 'create_select', user: @user, test: @test, question: @question, select: @select %>
  <% if @user.tests.any? %>
    <div class="col-md-7 white_block">
      <div class="center"><h4><%= t :分野 %>：<%= @test.subject %></h4></div>
      <div class="center"><h4><%= t :タイトル %>：<%= @test.title %></h4></div>
      <% @test.questions.each_with_index do |question, i| %>
        <div class="microposts">
          <li><%= t :問題 %>（<%= i+1 %>）</li>
          <%= question.Q %><br>
        </div>
        <div align="right">
          <%= link_to "delete question", test_question_path(@test,question),
              method: :delete,  data: { confirm: "You sure?" } %>
        </div>
        <% question.selects.each_with_index do |select, ia| %>
          <div class="quiz">
            <%= t :選択肢 %>（<%= ia+1%>）
            <%= select.judge == 1 ? "正解：" : "不正解：" %>
            <%= select.content %>
          </div>
        <% end %>
        <div align="right">
          <%= link_to "create selection", new_test_question_select_path(@test, question) %>
        </div>
      <% end %>
      <%= link_to new_test_question_path(@test) do %>
        <div class="btn btn-primary", "center">Add Question</div>
      <% end %>
    </div>
  <% end %>
</div>